%macro LIRT_LRT(H0_data1,HA_data2,Split);
    %LET Split=&Split.;
    proc sql noprint;
        select Value format=12.11 into :_ll_H0 from &H0_data1._logl;
        select Value format=12.11 into :_ll_HA from &HA_data2._logl;
    quit;
    proc sql noprint;
        select count(*) into : _nbParaH0 from &H0_data1._ipar;
		select count(*) into : _nbParaHA from &HA_data2._ipar;
    quit;
    proc sql noprint;
        select count(*) into : _nbDiscH0 from &H0_data1._disc;
		select count(*) into : _nbDiscHA from &HA_data2._disc;
    quit;
    proc sql noprint;
        select N_items into : _N_itH0 from &H0_data1._sizes;
        select N_values into : _N_valH0 from &H0_data1._sizes;
        select N_items into : _N_itHA from &HA_data2._sizes;
        select N_values into : _N_valHA from &HA_data2._sizes;
    quit;
	data &Split._lrt;
		length SP $ 12;
		N_it_H0=&_N_itH0;
		N_H0=&_N_valH0;
		N_it_HA=&_N_itHA;
		N_HA=&_N_valHA;
		if &_ll_H0>&_ll_HA then LLR_testsize=&_ll_H0-&_ll_HA; else LLR_testsize=.;
		LL_HA=&_ll_HA;
        LL_H0=&_ll_H0;
		N_Pa_H0=&_nbParaH0;
		N_Pa_HA=&_nbParaHA;
		N_Dis_H0=&_nbDiscH0;
		N_Dis_HA=&_nbDiscHA;
		DF=(&_nbParaHA+&_nbDiscHA)-(&_nbParaH0+&_nbDiscH0);
		SP="&Split.";
		if &_ll_H0>&_ll_HA then p_chisq=1-cdf('CHISQ',LLR_testsize,df); else p_chisq=.;
    run;
%mend LLRtest;

/*data &Split._lrt;length SP $ 10;LLR_testsize=.;ll_HA=.;ll_H0=.;nb_Para_H0=.;nb_Para_HA=.;df=.;sp="&Split.";p_chisq=.;run;*/
